apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j48t215ce-python
  janus-idp.io/tekton: j48t215ce-python
  backstage.io/kubernetes-id: j48t215ce-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j48t215ce-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
