apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: j48t215ce-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: j48t215ce-python 
  name: j48t215ce-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: j48t215ce-python
    weight: 100 
