apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: j48t215ce-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: j48t215ce-python 
  name: j48t215ce-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: j48t215ce-python 
